#include <stdio.h>
#include<time.h>
#include "mongo.h"

void push_int(char* nodeName, char* sensorName, int value);
void push_string(char* nodeName, char* sensorName, char* value);
int init();
int destroy();
long int timestamp();
char* getDbName();
void initEntry();
void pushEntry(char* dbName);
void initBT();
void createBT();

mongo conn[1];
bson b[1];
long int baseTime = 0;

int main() {
    init();
    printf("Base time: %ld\n", baseTime);

    //Pushing 2*2 data related to sensor1
    push_int("sensor1", "temp", 25);
    push_int("sensor1", "light", 50);

    sleep(2);

    push_int("sensor1", "temp", 24);
    push_int("sensor1", "light", 47);

    //Pushing 2*2 data related to sensor2
    push_int("sensor2", "temp", 12);
    push_int("sensor2", "light", 37);

    sleep(2);

    push_int("sensor2", "temp", 13);
    push_int("sensor2", "light", 39);

    destroy();
    return 0;
}


void createBT() {
    printf("Creating base time\n");
    baseTime = timestamp();
    bson_init( b );
    bson_append_long(b, "bt", baseTime);
    pushEntry("gateway.base");
}

/**
* Fetch base time from MongoDB, or initializes it
*/
void initBT() {
    mongo_cursor cursor[1];
    mongo_cursor_init(cursor, conn, "gateway.base" );

    if( mongo_cursor_next( cursor ) == MONGO_OK ) {
        bson_print( &cursor->current );
        bson_iterator iterator[1];
        if ( bson_find( iterator, mongo_cursor_bson( cursor ), "bt" )) {//base time is present in DB
            baseTime = bson_iterator_long( iterator );
            printf("Base time fetched from DB\n");
        } else {
            createBT();
        }
    } else {
        createBT();
    }

    mongo_cursor_destroy( cursor );
}

int init() {
    int status = mongo_client( conn, "127.0.0.1", 27017 );
    if( status != MONGO_OK ) {
        switch ( conn->err ) {
        case MONGO_CONN_NO_SOCKET:
            printf( "no socket\n" );
            return 1;
        case MONGO_CONN_FAIL:
            printf( "connection failed\n" );
            return 1;
        case MONGO_CONN_NOT_MASTER:
            printf( "not master\n" );
            return 1;
        }
        return conn->err;
    } else {
        initBT();
        return 0;
    }
}

int destroy() {
    mongo_destroy( conn );
    bson_destroy( b );
    return 0;
}


long int timestamp()
{
    return time(NULL);
}

char* getDbName(char* nodeName, char* sensorName) {
    char* dbName[256];
    strcpy(dbName, nodeName);
    strcat(dbName, ".");
    strcat(dbName, sensorName);
    return dbName;
}

//Note: timestamps are already included in autogenerated oid...
void initEntry() {
    bson_init( b );
    bson_append_long(b, "t", timestamp() - baseTime);
}

void push_int(char* nodeName, char* sensorName, int value) {
    initEntry();
    bson_append_int(b, "v", value);
    pushEntry(getDbName(nodeName, sensorName));
}

void push_string(char* nodeName, char* sensorName, char* value) {
    initEntry();
    bson_append_string(b, "v", value);
    pushEntry(getDbName(nodeName, sensorName));
}

void pushEntry(char* dbName) {
    printf("pushing data to: ");
    printf(dbName);
    printf("\n");
    mongo_write_concern options[1];
    mongo_write_concern_init(options);
    options->w = 1;//ack
    options->j = 1;//journaled
    mongo_write_concern_finish(options);

    bson_finish( b );
    mongo_insert( conn, dbName, b, options);
    bson_destroy( b );
}
